site_name: voluba-mriwarp User Documentation

repo_url: 'https://github.com/FZJ-INM1-BDA/voluba-mriwarp'
repo_name: 'GitHub'

copyright: 'Â© 2023, Forschungszentrum Juelich GmbH'

theme:
  name: readthedocs
  logo: 'images/voluba-mriwarp.png'

extra_css:
  - extra.css

docs_dir: docs

markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_markdown
  - footnotes
  - codehilite:
      use_pygments: False

nav:
  - About voluba-mriwarp: 'index.md'
  - 'installation.md'
  - 'usage.md'
  - 'acknowledgement.md'
  - Tutorials:
      - 'tutorial.md'
      - 'video_tutorial.md'
  - Contact us:
      - Support: 'mailto:support@ebrains.eu?subject=[voluba-mriwarp]'
      - GitHub Issues: 'https://github.com/FZJ-INM1-BDA/voluba-mriwarp/issues'
